import coffee4 from "@/assets/images/coffee-4.jpg";
import coffee5 from "@/assets/images/coffee-5.jpg";
import coffee6 from "@/assets/images/coffee-6.jpg";

export const images = {
  coffee4,
  coffee5,
  coffee6,
};

export const coffeeTypes = [
  {
    id: 0,
    name: "All Coffee",
    value: "all",
    description: "Show all coffee drinks",
    icon: "☕", // You can replace with an actual icon component
  },
  {
    id: 1,
    name: "Espresso",
    value: "espresso",
    description: "Strong concentrated coffee",
    icon: "⚫",
  },
  {
    id: 2,
    name: "Cappuccino",
    value: "cappuccino",
    description: "Espresso with steamed milk foam",
    icon: "🤎",
  },
  {
    id: 3,
    name: "Latte",
    value: "latte",
    description: "Espresso with lots of steamed milk",
    icon: "🥛",
  },
  {
    id: 4,
    name: "Mocha",
    value: "mocha",
    description: "Chocolate-flavored latte",
    icon: "🍫",
  },
  {
    id: 5,
    name: "Cold Brew",
    value: "cold_brew",
    description: "Slow-steeped cold coffee",
    icon: "🧊",
  },
  {
    id: 6,
    name: "Iced",
    value: "iced",
    description: "Chilled coffee drinks",
    icon: "❄️",
  },
  {
    id: 7,
    name: "Specialty",
    value: "specialty",
    description: "Unique coffee creations",
    icon: "🌟",
  },
];

export const coffeeDrinks = [
  {
    id: 1,
    name: "Espresso",
    type: "espresso",
    description:
      "A concentrated coffee beverage brewed by forcing hot water under pressure through finely ground coffee.",
    ingredients: ["Coffee beans", "Water"],
    preparationTime: 2,
    strength: 5,
    origin: "Italy",
    image: images.coffee4,
    price: 3.5,
    calories: 5,
    isHot: true,
    sizes: ["Single", "Double"],
    flavors: ["Bold", "Intense", "Robust"],
  },
  {
    id: 2,
    name: "Cappuccino",
    type: "cappuccino",
    description:
      "Espresso with steamed milk and a silky layer of foam, traditionally prepared with equal parts of each.",
    ingredients: ["Espresso", "Steamed milk", "Milk foam"],
    preparationTime: 5,
    strength: 3,
    origin: "Italy",
    image: images.coffee5,
    price: 4.75,
    calories: 120,
    isHot: true,
    sizes: ["Small", "Medium", "Large"],
    flavors: ["Creamy", "Balanced", "Mild"],
  },
  {
    id: 3,
    name: "Iced Americano",
    type: "iced",
    description:
      "Espresso shots topped with cold water and served over ice for a refreshing drink.",
    ingredients: ["Espresso", "Cold water", "Ice"],
    preparationTime: 3,
    strength: 4,
    origin: "United States",
    image: images.coffee6,
    price: 4.0,
    calories: 10,
    isHot: false,
    sizes: ["Medium", "Large"],
    flavors: ["Smooth", "Refreshing", "Clean"],
  },
  {
    id: 4,
    name: "Latte",
    type: "latte",
    description:
      "A milk coffee that is a made up of espresso and steamed milk with a small layer of foam.",
    ingredients: ["Espresso", "Steamed milk", "Light foam"],
    preparationTime: 6,
    strength: 2,
    origin: "Italy",
    image: images.coffee4,
    price: 5.25,
    calories: 150,
    isHot: true,
    sizes: ["Small", "Medium", "Large"],
    flavors: ["Mild", "Sweet", "Creamy"],
  },
  {
    id: 5,
    name: "Mocha",
    type: "mocha",
    description:
      "A chocolate-flavored variant of a latte made with espresso, steamed milk, and chocolate syrup.",
    ingredients: [
      "Espresso",
      "Steamed milk",
      "Chocolate syrup",
      "Whipped cream",
    ],
    preparationTime: 7,
    strength: 3,
    origin: "United States",
    image: images.coffee5,
    price: 5.75,
    calories: 250,
    isHot: true,
    sizes: ["Medium", "Large"],
    flavors: ["Chocolatey", "Sweet", "Rich"],
  },
  {
    id: 6,
    name: "Cold Brew",
    type: "cold_brew",
    description:
      "Coffee steeped in cold water for 12-24 hours, resulting in a smooth, less acidic drink.",
    ingredients: ["Coffee grounds", "Cold water"],
    preparationTime: 1440,
    strength: 4,
    origin: "Japan",
    image: images.coffee6,
    price: 4.5,
    calories: 5,
    isHot: false,
    sizes: ["Small", "Medium", "Large"],
    flavors: ["Smooth", "Low acidity", "Sweet"],
  },
  {
    id: 7,
    name: "Flat White",
    type: "latte", // Could also create a separate "flat_white" type
    description:
      "Similar to a latte but with a higher ratio of coffee to milk and a velvety microfoam.",
    ingredients: ["Espresso", "Steamed milk"],
    preparationTime: 5,
    strength: 4,
    origin: "Australia/New Zealand",
    image: images.coffee4,
    price: 5.0,
    calories: 110,
    isHot: true,
    sizes: ["Small", "Medium"],
    flavors: ["Strong", "Velvety", "Rich"],
  },
  {
    id: 8,
    name: "Affogato",
    type: "specialty",
    description:
      "A dessert coffee made by pouring a shot of hot espresso over vanilla ice cream.",
    ingredients: ["Espresso", "Vanilla ice cream"],
    preparationTime: 3,
    strength: 3,
    origin: "Italy",
    image: images.coffee5,
    price: 6.0,
    calories: 200,
    isHot: false,
    sizes: ["One size"],
    flavors: ["Sweet", "Creamy", "Bittersweet"],
  },
];
